[aws]
region = us-east-1  

[database]
use_secrets_manager = true  
secret_name = vrse_db
; default_host = vrse-aurora-rds-postgres.cluster-c9sseesmulb1.us-east-1.rds.amazonaws.com
; dbname = anatomy_db
; default_port = 5432
